### ISSUE TITLE
Why R_t_c? 

### ISSUE THREAD

**Issue by yujiaguo** [LarryDong/HandEye-Tsai#1]
感觉不应该是R_t_c啊，应该是R_c_t才对啊 ，还有想问一下算相机在世界坐标系（estimateWorldCameraPose）的意义是什么呢，为什么不能直接用标定的外方位元素呀

**Comment by LarryDong** [comment]
1. R_t_c指从将相机坐标系下的一点坐标换算到target系的旋转；和其他量的定义一致就行，怎么定义变换顺序是你自己决定的。
2. 不了解“外方位元素”这套表示方法。
3. 请先熟悉手眼标定的基本目的和参数表示以及方法原理，我不清楚你这边有没有搞清楚。可参考我的[CSDN博客](https://blog.csdn.net/tfb760/article/details/122190290)
