### ISSUE TITLE
请问这套算法最终的精度可以达到什么量级呢？

### ISSUE THREAD

**Issue by Cerf-Volant425** [LarryDong/HandEye-Tsai#2]
谢谢！

**Comment by LarryDong** [comment]
不知道呀。精度和传感器精度、数据采集啥的都有关。
我自己采集的数据，测量平移误差应该是在几个mm以内，但我也不知道镜头光心具体位置不知道具体差多少。
代码有提供仿真数据，你自己可以加不同程度噪声看下噪声的影响有多大。

**Comment by Cerf-Volant425** [comment]
感谢董博的回复！借此机会还想请教您一个问题，Vicon或者相机从topic生成，到topic传输到设备上被打上时间戳的这个readout delay，有什么方式消除吗?
我的vicon发布的真值是网线传输，相机发布的图片是usb传输，都传到同一台PC上（make sure on a same clock），但感觉这个delay会导致图片和真值的时间戳不同步，从而影响手眼标定的精度。

**Comment by LarryDong** [comment]
外部硬件同吧，vicon都有，相机一般的也有。
不能硬件同步，你每个位置摆着静止不动几秒，然后换下一个。只用稳定下来的数据，也可以。

**Comment by Cerf-Volant425** [comment]
好的谢谢。
